import { useEffect, useState } from "react";
import useScrollListener from "../hooks/scroll";
import LegalAccordion from "../components/LegalAccordion";
import { Data2 } from "../components/Data2";

const legal = () => {
    
    return (
        <div className="lg:max-w-1120 md:max-w-544 lg:max-w-1120my-0 mx-auto px-6 lgg:px-0 relative">
            <h1 className="font-body font-bold text-8xl md:text-9xl text-secondary mt-16 lg:mt-32 mb-16 lg:mb-20">POLICIES</h1>
            <div className="lg:flex justify-between">
                <div>
                    <div className="mb-16 md:pr-12 max-w-352 w-full stick">
                        <LegalAccordion data={Data2} />
                    </div>
                </div>
                
                <div className='md:max-w-544 w-full  lg:max-w-640'>
                    <div className="border-b-2 border-line pb-12 mb-12">
                        <h2 className="text-secondary text-3xl font-semibold mb-12">Privacy Policy</h2>
                        <div className="text-lg">
                            <p className="pb-8">Last updated: August 9, 2021.</p>
                            
                            <p className="pb-8">
                                 The WebstaurantStore, Inc. ("us", "we", or "our") operates the https://www.webstaurantstore.com/ website (hereinafter referred to as the "Service").
                            </p>
                            <p className="pb-8" >
                                This page informs you of our policies regarding the collection, use and disclosure of personal and other data when you use our Service and the choices you have associated with that data. This Privacy Policy applies to the information that The WebstaurantStore, Inc. and its affiliates collect through the Service and other websites, online features, applications, products and services owned or controlled by such companies and affiliates or that post a link to this Privacy Policy (collectively, the “Sites”).
                            </p>
                            <p>
                                We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from this page.
                            </p>
                        </div>
                    </div>

                    <div className="border-b-2 border-line pb-12 mb-12">
                        <h2 id="definitions" className="text-secondary text-3xl font-semibold mb-12">Definitions</h2>
                        <div className="text-lg">
                            <div>
                                <p className="pb-8">
                                    <span className="font-bold">Service</span><br />
                                    Service is the website operated by the WebstaurantStore, Inc. that can be found at: “https://www.webstaurantstore.com”
                                </p>
                                <p className="pb-8">
                                    <span className="font-bold">Personal Data</span><br />
                                    Personal Data means data about a living individual who can be identified from this data (or from those and other information either in our possession or likely to come into our possession).
                                </p>
                                <p className="pb-8">
                                    <span className="font-bold">Usage Data</span><br />
                                    Usage Data is data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
                                </p>
                                <p className="pb-8">
                                    <span className="font-bold">Cookies</span><br />
                                    Cookies are small files stored on your device (computer or mobile device).
                                </p>
                            </div>
                        </div>
                    </div>

                    <div className="border-b-2 border-line pb-12 mb-12">
                        <h2 id="collection" className="text-secondary text-3xl font-semibold mb-12">Information Collection and Use</h2>
                        <div className="text-lg">
                        
                            <p className="pb-8">
                                We collect several different types of information for various purposes to provide and improve our service to you.
                            </p>
                                
                            <p className="pb-8 font-bold text-xl">Types of Data Collected</p>

                            <p>
                                <span className="font-bold">Personal Data</span><br />
                                
                                While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:
                            </p>

                            <ul className="ml-2 mb-6 bullet list-disc list-inside">
                                <li><span>Email address</span></li>
                                <li><span>First name and last name</span></li>
                                <li><span>Phone number</span></li>
                                <li><span>Address, State, Province, ZIP/ Postal code, City</span></li>
                                <li><span>Organization name and/or job title</span></li>
                                <li><span>Cookies and Usage Data</span></li>
                            </ul>
                                
                            <p className="pb-8">
                                <span className="font-bold">Usage Data</span><br />
                                
                                We may also collect information on how the Service is accessed and used and your online activity ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers, The WebstaurantStore, Inc. e-mails you open and/or forward, the purchases and transactions you make through the Service and other diagnostic data. We may associate Data Usage with you as a specific and identifiable person. When we do so, we treat the combined information as personal information.
                            </p>

                            <p className="pb-8">
                                <span className="font-bold">Tracking Cookies Data</span><br />
                                We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.
                                Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service.
                                You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
                            </p>

                            <p>Examples of Cookies we use:</p>
                                <ul className="ml-2 mb-6 bullet list-disc list-inside">
                                    <li>
                                        <p className="text-lg font-bold inline-block">Session Cookies.</p> <span className="inline-block"> We use Session Cookies to operate our Service. </span>
                                    </li>
                                    <li>
                                        <p className="text-lg font-bold inline-block">Preference Cookies.</p> <span> We use Preference Cookies to remember your preferences and various settings. </span>
                                    </li>
                                    <li>
                                        <p className="text-lg font-bold inline-block">Security Cookies.</p> <span> We use Security Cookies for security purposes. </span>
                                    </li>
                                </ul>
                                
                            <p>
                                We may combine certain automatically collected information with other information we obtain about you, which may include data we obtain from third parties. Information about your use of the Sites and other websites may be collected across time, devices, and websites for various purposes, including to associate different devices you use and to deliver relevant and/or retargeted content. If you choose not to provide the personal information we reasonably require, it may hinder our ability to provide the information or services you have requested.
                            </p>
                        </div>
                    </div>

                    <div className="border-b-2 border-line pb-12 mb-12">
                        <h2 id="data-use" className="text-secondary text-3xl font-semibold mb-12">Use of data</h2>
                        <div className="text-lg">
                            <p>
                                The WebstaurantStore, Inc. uses the collected data for various purposes:
                            </p>
                            <ul className="ml-6 mb-6 bullet list-disc list-outside">
                                <li><span>To provide and maintain our Service</span></li>
                                <li><span>To notify you about changes to our Service</span></li>
                                <li><span>To allow you to participate in interactive features of our Service when you choose to do so</span></li>
                                <li><span>To provide customer support</span></li>
                                <li><span>To gather analysis or combine all of the information we collect about you so that we can enhance and improve the Service and our products and services</span></li>
                                <li><span>To monitor the usage of our Service</span></li>
                                <li><span>To administer and develop our business relationship with you and the company you represent</span></li>
                                <li><span>To detect, prevent and address technical issues</span></li>
                                <li><span>To send personal data to third-party service providers for payments, fraud prevention and shipping</span></li>
                                <li><span>To contact you about our own and third-parties’ goods and services that may be of interest to you</span></li>
                                <li><span>To enable us to display advertisements to our advertisers’ target audiences (even though we do not disclose your own personal information for these purposes without your consent, if you click on or otherwise interact with an advertisement, the advertiser may assume that you meet its target criteria)</span></li>
                                <li><span>In any other way we may describe to you when you provide the information</span></li>
                                <li><span>For any other purpose with your consent</span></li>
                            </ul>
                        </div>
                    </div>

                    <div className="border-b-2 border-line pb-12 mb-12">
                        <h2 id="data-transfer" className="text-secondary text-3xl font-semibold mb-12">Transfer of data</h2>
                        <div className="text-lg">
                            <p className="pb-8">
                                Your information, including Personal Data, may be transferred to and maintained on computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.
                                If you are located outside of the United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to the United States and process it there.
                            </p>  

                            <p className="pb-8">
                                Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
                            </p>
                            <p>
                                The WebstaurantStore, Inc. will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy. No transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information. 
                            </p>
                        </div>
                    </div>

                    <div id="disclosure" className="border-b-2 border-line pb-12 mb-12">
                        <h2 className="text-secondary text-3xl font-semibold mb-12">Disclosure of data</h2>
                        <div className="text-lg">
                            <p>
                                Disclosure for Law Enforcement <br />
                                Under certain circumstances, The WebstaurantStore, Inc. may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
                            </p>
                            <p>
                                <span className="font-bold">Legal Requirements</span><br />
                                The WebstaurantStore, Inc. may disclose your Personal Data in the good faith belief that such action is necessary to: 
                            </p>
                            <ul className="ml-6 mb-6 bullet list-disc list-outside">
                                <li><span>To comply with a legal obligation</span></li>
                                <li><span>To protect and defend the rights or property of The WebstaurantStore, Inc.</span></li>
                                <li><span>To prevent or investigate possible wrongdoing in connection with the Service</span></li>
                                <li><span>To protect the personal safety of users of the Service or the public</span></li>
                                <li><span>To protect against legal liability</span></li>
                            </ul>
                            
                            <p className="pb-8">
                                <span className="font-bold">Disclosure to Affiliates</span><br />
                                We may share information, including personal information, as applicable, within The WebstaurantStore, Inc. and among our affiliates, primarily for business and operational purposes.
                            </p>          

                            <p>
                                <span className="font-bold">Disclosure for Third-Party of Targeted Advertising</span><br />
                                We may also disclose your personal information to third parties to market their products or services to you if you have not opted out of these disclosures. If you do not want us to share your personal information with unaffiliated or non-agent third parties for promotional purposes or if you do not want us to use information that we collect or that you provide to us to deliver advertisements according to our advertisers’ target-audience preferences, you can opt out by emailing privacy@webstaurantstore.com.
                            </p>                  
                            
                            <p>
                                We do not control third parties’ collection or use of your information to serve interest-based advertising. However, these third parties may provide you with ways to choose not to have your information collected or used in this way. You can opt out of receiving targeted ads from members of the National Advertising Initiative (“NAI”) on the NAI's website.
                            </p>
                        </div>
                    </div>

                    <div id="security" className="border-b-2 border-line pb-12 mb-12">
                        <h2 className="text-secondary text-3xl font-semibold mb-12">Security of data</h2>
                        <div className="text-lg">
                            <p>
                                The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
                            </p>
                        </div>
                    </div>

                    <div className="border-b-2 border-line pb-12 mb-12">
                        <h2 id="oppa" className="text-secondary text-3xl font-semibold mb-12">Our Policy on “Do Not Track” Signals under the California Online Privacy Protection Act (CalOPPA)</h2>
                        <div className="text-lg">
                            <p className="pb-8">
                            We do not support Do Not Track ("DNT"). Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.
                            </p>

                            <p>
                                You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.
                            </p>
                        </div>
                    </div>

                    <div className="border-b-2 border-line pb-12 mb-12">
                        <h2 id="providers" className="text-secondary text-3xl font-semibold mb-12">Service Providers</h2>
                        <div className="text-lg">
                            <p className="pb-8">
                                We may employ third party companies and individuals to facilitate our Service ("Service Providers"), provide the Service on our behalf, perform Service-related services or assist us in analyzing how our Service is used.
                                These third parties have access to your Personal Data only to perform these tasks on our behalf and are contractually obligated not to disclose or use it for any other purpose.
                            </p>

                            <p className="pb-8">
                                <span className="font-bold">Behavioral Remarketing</span><br />
                                The WebstaurantStore, Inc. uses remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies (either alone or in conjunction with web beacons or other tracking technologies) to collect information about you to inform, optimize, and serve ads based on your past visits to our Service. This collected information may be associated with your personal information and may also be about your online activities over time and across different websites and other online services. We currently work with the following third-party vendors:
                            </p>

                            <p className="pb-8">
                                <span className="font-bold">Google Ads (AdWords)</span><br />
                                Google Ads (AdWords) remarketing service is provided by Google Inc. You can opt-out of Google Analytics for Display Advertising and customize the Google Display Network ads by visiting the <a className="text-primary" href="https://ads.google.com/home/#!/">Google Ads</a>  settings page.
                            </p>

                            <p className="pb-8">
                                Google also recommends installing the Google Analytics <a className="text-primary" href="/">Opt-out Browser Add-On</a>  for your web browser.
                            </p>

                            <p className="pb-8">
                                Google Analytics Opt-Out Browser Add-On provides visitors with the ability to prevent their data from being collected and used by Google Analytics. For more information on the privacy practices of Google, please visit the <a className="text-primary" href="https://policies.google.com/privacy?hl=en-US">Google Privacy Terms</a> web page.
                            </p>
                            
                            <p className="pb-8">
                                <span className="font-bold">Display & Video 360 (a Google product)</span><br />
                                For more information on Display & Video 360 conversion tracking visit Google’s Privacy & Terms.
                            </p>
                            
                            <p className="pb-8">
                                <span className="font-bold">Yahoo Dot Tags</span><br />
                                For more information on Yahoo Dot Tags visit <a className="text-primary" href="">Yahoo's site.</a> 
                            </p>

                            <p className="pb-8">
                                <span className="font-bold">Facebook</span><br />
                                For more information on Facebook Ads Pixel, visit <a className="text-primary" href="">Facebook's Business Page.</a> 
                            </p>

                            <p className="pb-8">
                                <span className="font-bold">Bing</span><br />
                                For more information on Microsoft Bing Ads, visit <a className="text-primary" href="">Bing Ads Help.</a> 
                            </p>

                            <p className="pb-8">
                                <span className="font-bold">Pinterest</span><br />
                                For more information on Pinterest Tag tracking, visit <a className="text-primary" href="">Pinterest's site.</a> 
                            </p>
                            
                            <p className="pb-8">
                                <span className="font-bold">LinkedIn</span><br />
                                For more information on Linkedin Insight Tags, visit <a className="text-primary" href="">LinkedIn's site.</a> 
                            </p>
                            
                            <p>
                                We do not control these third-parties’ tracking technologies or how they may be used. If you have any questions about an advertisement or other targeted content, including how to opt out of receiving targeted advertising from these vendors, you should contact the responsible provider directly.
                            </p>
                         </div>
                    </div>

                    <div className="border-b-2 border-line pb-12 mb-12">
                        <h2 className="text-secondary text-3xl font-semibold mb-12">Children’s Privacy</h2>
                        <div className="text-lg">
                            <p className="pb-8">
                                Our Service does not address anyone under the age of 18 (“Children”). 
                            </p>

                            <p>
                                We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.
                            </p>
                        </div>
                    </div>

                    <div className="border-b-2 border-line pb-12 mb-12">
                        <h2 className="text-secondary text-3xl font-semibold mb-12">Changes to This Privacy Policy</h2>
                        <div className="text-lg">
                            <p className="pb-8">
                                We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. 
                            </p>

                            <p>
                                You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
                            </p>
                        </div>
                    </div>

                    <div className="pb-12 mb-12">
                        <h2 className="text-secondary text-3xl font-semibold mb-12">Contact us</h2>
                        <div className="text-lg">
                            <p className="pb-8">
                                If you have any questions about this Privacy Policy, please contact us.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}

export default legal;